"""empty message

Revision ID: 035c74b6dd26
Revises: a66c9c39f6c2
Create Date: 2019-04-17 14:09:56.909466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035c74b6dd26'
down_revision = 'a66c9c39f6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('club_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'club_id')
    # ### end Alembic commands ###
